title: "Joey Tuason: Data Science Portfolio"
logo: "/images/beach.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data science enthusiast with passion to explore Machine Learning models
  <br><br>
  Currently working as an actuary
  <br><br>
  An advocate for the WFH movement -- I believe this is the future
  <br><br>
  Never (and never will be) a boomer 
  <br><br>
  <a href="http://www.linkedin.com/in/jose-mari-tuason-a0538820">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
