title: "Joey Tuason: Data Science Portfolio"
logo: "/images/1516893019054.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data science enthusiast with passion to explore Machine Learning models
  <br><br>
  Currently working as an actuary 
  <br><br>
  <a href="http://www.linkedin.com/in/jose-mari-tuason-a0538820">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
